name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Prepare Laravel Application
      run: |
        cp .env.test .env
        php artisan key:generate
    - name: Install Node.js dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
        APP_KEY: ${{ secrets.APP_KEY }}
      # run: vendor/bin/phpunit --testsuite Unit
      run: vendor/bin/phpunit tests/